// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Anchor: typeof import('./../components/anchor.vue')['default']
    AnchorItem: typeof import('./../components/anchor-item.vue')['default']
    AnchorList: typeof import('./../components/anchor-list.vue')['default']
    HeroCode: typeof import('./../components/hero-code.vue')['default']
    LinkList: typeof import('./../components/link-list.vue')['default']
    PageFooter: typeof import('./../components/page-footer.vue')['default']
    PageHeader: typeof import('./../components/page-header.vue')['default']
    PageMain: typeof import('./../components/page-main.vue')['default']
    PostAnchor: typeof import('./../components/post-outline.vue')['default']
    PostComment: typeof import('./../components/post-comment.vue')['default']
    PostDetail: typeof import('./../components/post-detail.vue')['default']
    PostItem: typeof import('./../components/post-item.vue')['default']
    PostList: typeof import('./../components/post-list.vue')['default']
    PostMain: typeof import('./../components/post-main.vue')['default']
    PostOutline: typeof import('./../components/post-outline.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SButton: typeof import('./../components/s-button.vue')['default']
    SCard: typeof import('./../components/s-card.vue')['default']
    SHeroCode: typeof import('./../components/s-hero-code.vue')['default']
    STag: typeof import('./../components/s-tag.vue')['default']
    Tag: typeof import('./../components/tag.vue')['default']
  }
}
